[package]
name = "cdbs-app"
version = "0.1.0"
authors = ["I_Nosovskiy <mananaxep@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# You should include "rlib" (the default crate type) otherwise your crate can't be used as a Rust library
# which, among other things, breaks unit testing
# crate-type = ["rlib", "cdylib"]

[dependencies]
yew = "0.17.4"
wasm-bindgen = "0.2.73"
yew-router = "0.14.0"
yewtil = "0.3.2"
wasm-logger = "0.2"

instant = { version = "0.1", features = ["wasm-bindgen"] }
lipsum = "0.7"
log = "0.4"
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.7", features = ["small_rng", "wasm-bindgen"] }

chrono = { version = "0.4.10", features = ["serde"] }
dotenv_codegen = "0.15.0"
lazy_static = "1.4.0"
# log = "0.4.8"
parking_lot = "0.10.0"
pulldown-cmark = "0.6.1"
serde = "1.0.104"
serde_json = "1.0.44"
thiserror = "1"
# yew = "0.17.3"
# yew-router = { version="0.14.0", features = ["web_sys"] }
# wasm-bindgen = "0.2.63"
# wasm-logger = "0.2.0"
# wee_alloc = "0.4.5"

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  "Node",
  "Window",
  "HtmlCollection",
]

[dev-dependencies]
js-sys = "0.3.37"
wasm-bindgen-futures = "0.4.10"
wasm-bindgen-test = "0.3.10"
