use super::MAX_KEY;

/// Translation of the fields for English
pub(crate) const LOCAL_EN: [&str; MAX_KEY] = [
    "",
    "engineer",
    "component",
    "supplier",
    "Information about 3D models, drawings, standards, suppliers",
    "Automation of access to the platform via API and integration with CAD systems",
    "Publishing Vendor and Custom Component Catalogs",
    "Exchange of information about components, standards and manufacturers",
    "English",
    "Russian",
    "Terms",
    "What is?",
    "API reference",
    "Sign in",
    "Sign up",
    "Profile",
    "Settings",
    "Logout",
    "Need an account?",
    "Username",
    "Password",
    "Have an account?",
    "Email",
    "Firstname",
    "Lastname",
    "Secondname",
    "Program",
    "Region",
    "by registering account you accept this agreement",
    "terms and conditions",
    "Updated at: ",
    "Followers: ",
    "CERTIFICATES",
    "COMPONENTS all",
    "fav COMPONENTS",
    "COMPANIES all",
    "fav COMPANIES",
    "fav STANDARDS",
    "fav USERS",
    " Position: ",
    " Region: ",
    " Working software: ",
    "Hide info",
    "Show info",
    "Login",
    "Create",
    "Save",
    "Delete profile data",
    "Old password",
    "New password",
    "Username",
    "Company type",
    "Firstname",
    "Lastname",
    "Secondname",
    "Position",
    "Phone",
    "Address",
    "Type access",
    "Change",
    "Managing modifications of the component",
    "Description",
    "Input your password for confirm delete profile",
    "Profile",
    "Certificates",
    "Access",
    "Site",
    "Remove profile",
    "Updated access",
    "Updated password",
    "Profile delete",
    "this removed all data related with profile, it cannot be canceled!",
    "Updated rows: ",
    "Last updated: ",
    "No certificates found",
    "no data",
    "Open profile",
    "Profile",
    "Profile picture",
    "Select a supplier",
    "Access Policy",
    "* please note that login is by username, not email.",
    "Remove profile",
    "Upload new certificate",
    "It is recommended to upload the certificate in image format.",
    "Files selected for upload",
    "Certificate file",
    "Upload",
    "Clear",
    "Success",
    "Certificate uploaded!",
    "Company logo",
    "Image updated!",
    "Image file",
    "user uploaded ",
    "updated at ",
    "Life cycle stage",
    "Component type",
    "See more",
    "See less",
    "Modifications",
    "Сharacteristics",
    "Component Files",
    "Standards",
    "Catalogs",
    "Keywords",
    "Files from the file set of the selected modification",
    "Suppliers",
    "Main supplier",
    "Company",
    "Name",
    "Action",
    "Classifier",
    "Specified tolerance",
    "Attention!",
    "Back",
    "Basic Info",
    "Add",
    "Created by user",
    "Files of the selected modification",
    "Filename",
    "Content",
    "Filesize",
    "Add a supplier for the component",
    "Upload by",
    "Upload at",
    "Download",
    "Edit",
    "Info",
    "Select",
    "Adding a parameter and its value",
    "Adding a value for the modification parameter",
    "Change the value",
    "Set a value",
    "Change value",
    "Delete",
    "No additional parameters",
    "Get link",
    "Files from the file set for ",
    "Certificate removed!",
    "Description updated!",
    "Owner: ",
    "Classifier: ",
    "Show standard",
    "Specified tolerance: ",
    "type access ",
    "classifier",
    "specified tolerance",
    "technical committee",
    "publication at",
    "standard status",
    "region",
    "Сharacteristics of the standard",
    "Files of the standard",
    "Components",
    "Publication at",
    "Updated at",
    "Managing master data of the standard",
    "Supplier",
    "LCS",
    "manufactured by ",
    "Open",
    "License",
    "Reg.№ ",
    "Region: ",
    "Show company",
    "Add supplier for component",
    "Set owner supplier",
    "Select supplier",
    "Supplier description",
    "Orgname",
    "Shortname",
    "Modification Files",
    "Filesets",
    "Add new modification",
    "Create new modification",
    "Modification name",
    "Modification Data",
    "Parameter",
    "Value",
    "Add parameter",
    "Adding a parameter to the component",
    "Select preview image",
    "Possible format",
    "Update Preview",
    "Manage component characteristics",
    "Upload component files",
    "Manage component files",
    "Files for component",
    "Manage component standards",
    "Manage component suppliers",
    "Add standard for component",
    "Enter data for catalogs search",
    "Enter keywords separated by spaces or commas",
    "No file uploaded",
    "Select files for fileset",
    "Add fileset",
    "Upload files for fileset",
    "Files of fileset",
    "Open component",
    "Select files for component",
    "Select files for modification",
    "Upload modification files",
    "Files for modification",
    "Files not found",
    "Set a paramname (letter case has matter)",
    "Adding a set of files",
    "Select a set of files",
    "Paste the copied table data here.",
    "Importing component parameters",
    "Name of parameter",
    "Changing the parameter value",
    "Select standard",
    "Data updated! Change rows:",
    "Data updated",
    "Change represent",
    "Representation type",
    "Delete component",
    "For confirm deleted all data this ",
    " component enter this uuid:",
    "Yes, delete",
    "Cancel",
    "Choose files for standard…",
    "Owner company",
    "Manage characteristics of the standard",
    "Files of the standard",
    "Open standard",
    "Delete standard",
    " standard enter this uuid:",
    "Set characteristics for the standard",
    "New representative",
    "Here since",
    "Information",
    "Type",
    "To upload data, simply copy the data from a spreadsheet (Excel, LibreOffice, etc.) and paste it into the field below.",
    "To add and change the component parameters, you need to insert data into two columns. The first column contains the names of the parameters, and the second column contains their values.<br/>The values specified for the parameters must be different from the existing values.",
    "Filename",
    "Content type",
    "Filesize",
    "Program",
    "Upload by",
    "Upload at",
    "Created at",
    "* keywords must be less than 100 characters",
    "Add a license for a component",
    "Select a license",
    "ID:",
    "Patch:",
    "Error loading model",
    "Unsupported format",
    "Original Textures",
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
    "Controls",
    "Material",
    "Making The Present Better",
    "Lighting",
    "Overviews",
    "Version ",
    "© CADBase Platform",
    "Glossary",
    "Model Info",
    "Show profile",
    "Filename: ",
    "Adding a standard to the component",
    "Update Company",
    "Open company",
    "Representations",
    "Remove company",
    "Delete company",
    "Privacy Notice",
    "Company don't have representations",
    "Update access",
    "Warning: ",
    "All company-related data will be permanently deleted with no possibility of recovery!",
    "Company delete",
    " supplier",
    "Created at",
    "Updated at",
    " Email: ",
    " Phone: ",
    " Reg.№ ",
    " Location: ",
    " Site: ",
    "Sphere of activity",
    "Notifications",
    "CADBase conditions",
    "Members",
    "If you need support or help, please contact us: ",
    "Great!",
    "Create company",
    "Create component",
    "Create standard",
    "Representative removed!",
    "Representative created!",
    "No child component available",
    "Hide components",
    "See components",
    "No file to display (search is performed in the selected fileset)",
    "Expand",
    "Collapse",
    "View",
    "Close",
    "Coordinate axes",
    "Rotation",
    "Frame",
    "Model color",
    "Background color",
    "Model Scale",
    "Revision",
    "Rev.",
    "Size",
    "Uploaded",
    "Created",
    "Loaded",
    "Hide",
    "Show",
    "bytes",
    "KB",
    "MB",
    "GB",
    "TB",
    "* pay attention to the correct character order, case and input language when entering data.",
    "Copy",
    "Copied",
    "No result",
    "Open 3D view",
    "Add to bookmarks",
    "Remove from bookmarks",
    "Share",
    "Show files of the selected modification",
    "Managing files of the standard",
    "Upload files for the standard",
    "Unauthorized",
    "Go to page authorization",
    "Edit",
    "Preview",
    "Markdown markup language is supported",
    "For example, the <sup></sup> tag is used to specify superscript characters, and «m<sup>2</sup>» is used to spell square meter.",
    "Message to change",
    "Messages will help understand: Why was this change made? What effect did the change have? Why was this change necessary?",
    "The maximum message length is 500 characters",
    "Message",
    "Import modifications and parameters",
    "The first row of the table is used to specify parameter names.<br/>Keywords are used to specify modifications data:<br/><b>[ModificationName]</b> - column with modification names (required),<br/><b>[ModificationDescription]</b> - column with descriptions,<br/><b>[ModificationActualStatusId]</b> - column for state IDs.",
    "Example:\n[ModificationName]\tparameter 1\tparameter 2\nmodification name 1\tvalue 1\tvalue 2\nmodification name 2\tvalue 3\tvalue 4",
    "headers",
    "rows",
    "Import",
    "Export",
    "Search",
    "No results",
    "Enter search text",
    "Component",
    "Data of the selected modification",
    "Order calculation",
    "Request",
    "Cost:",
    "Laser cutting calculator",
    "Calculate the cost of cutting before creating an order",
    "Material thickness (mm)",
    "Material",
    "Total length of cut (m)",
    "Total number of cuts (pcs)",
    "Calculate",
    "Create order",
    "Steel",
    "Stainless steel",
    "Pure aluminum",
    "Aluminum alloys (AMg, AMz)",
    "Duralumin (D16)",
    "Brass",
    "Copper",
    "Titanium",
    "Managing master data of the service",
    "Manage characteristics of the service",
    "Managing files of the service",
    "Files of the service",
    "Upload files for the service",
    "Open service",
    "Services",
    "Discussion",
    "Post",
    "Reply",
    "Show answers",
    "Enter a new comment",
    "By parameters",
    "By catalogs (categories)",
    "By keywords",
    "Only favorites",
    "Refinement filters",
    "Search by ID",
    "By company",
    "By standard",
    "By user",
    "Enter UUID",
    "Reset selection",
    "New modification",
    "Data not available",
    "Permission based access for users/groups",
    "Some data is available to users",
    "Available to all users",
    "A file set (fileset) is a logical group of files linked to a specific component modification.",
    "For the selected component modification a file set is missing, so file upload is currently unavailable.",
    "No filesets",
    "Filesets",
    "Choose a name for the set (for example, “FreeCAD”, “Blender”, “GLTF”, etc.).",
    "Save the set – after that you will be able to upload files to it.",
    "A component modification is an individual variant or version of a component that captures specific parameters, material, dimensions, configuration, and other product characteristics.",
    "This action will place this object, including all its related data, in a pending deletion state and delete it permanently.",
    "Are you absolutely sure?",
    "After this point, ",
    " data cannot be recovered.",
    "This action can lead to data loss. To prevent accidental actions we ask you to confirm your intention.",
    "Enter the following to confirm:",
    "SERVER LOCATION",
    "🇳🇱 Netherlands",
    "🇷🇺 Russia",
    "🇨🇳 China",
    "🌐 Custom Server",
    "View",
    "Active Layer",
    "Hide Travel Moves",
    "Display",
    "Play",
    "Speed",
    "Select",
    "Metalness",
    "Roughness",
    "Env Intensity",
    "Clearcoat",
    "Clearcoat Rough",
    "Ambient",
    "Directional",
    "Light",
    "File",
    "Size",
    "F: fullscreen | 0-9: views (5: ortho/persp)",
    "Hide Textures",
    "all",
    "up to current",
    "current only",
    "Perspective (3D)",
    "Top (XY)",
    "Bottom",
    "Front (XZ)",
    "Back",
    "Left (YZ)",
    "Right",
    "Isometric",
    "Drag here or click to select",
    "Files to upload",
    "Pending",
    "Uploading",
    "Completed",
    "Failed",
    " file(s) are in storage and awaiting confirmation",
    " file(s) failed to upload",
    "Upload URL not found",
    "Granted At",
    "Users Access",
    "Companies Access",
    "Actions",
    "Company Roles & Permissions",
    "New Role",
    "No Roles Yet",
    "Roles help you organize team members and control their access to company resources.",
    "Create First Role For The Company",
    "Role Name",
    "Access Permissions",
    "No permissions",
    "Create Company Role",
    "Role",
    "Type to new role name...",
    "Edit Role",
    "Role ID:",
    "Select which permissions this role should have",
    "This role will have no permissions. Members with this role won't be able to do anything.",
    "Company Members",
    "Add Member",
    "Manage team members can do access your company.",
    "No members in this company.",
    "Type to search users...",
    "Type to search companies...",
    "Joined At",
    "Add User",
    "Add User Access",
    "Search User",
    "Access Level",
    "Add Company Access",
    "Search Company",
    "Add Company Member",
    "Add Company",
    "No users found",
    "Found:",
    "Avatar",
    "No users have access to this component.",
    "No companies found",
    "No companies have access to this component.",
    "Customize roles to control what team members can do within your company.",
    "Select fileset",
    "Start typing name...",
    "Saving selection...",
    "Hemisphere",
    "Key Light",
    "Fill Light",
    "Rim Light",
    "Key Light Position",
    "Fill Light Position",
    "Rim Light Position",
    "Intensities",
    "Positions",
];