use std::collections::BTreeMap;
use lazy_static::lazy_static;

lazy_static! {
    /// Translation of the fields for English
    pub(super) static ref LOCAL_EN: BTreeMap<usize, &'static str> = BTreeMap::from([
            (1, "engineer"),
            (2, "component"),
            (3, "supplier"),
            (4, "A wide range of different components & component catalogs"),
            (5, "Constantly updated component base"),
            (6, "Ability to add custom components"),
            (7, "Buying and selling components"),
            (8, "English"),
            (9, "Russian"),
            (10, "Terms"),
            (11, "About us"),
            (12, "API reference"),
            (13, "Sign in"),
            (14, "Sign up"),
            (15, "Profile"),
            (16, "Settings"),
            (17, "Logout"),
            (18, "Need an account?"),
            (19, "Username"),
            (20, "Password"),
            (21, "Have an account?"),
            (22, "Email"),
            (23, "Firstname"),
            (24, "Lastname"),
            (25, "Secondname"),
            (26, "Program"),
            (27, "Region"),
            (28, "by registering account you accept this agreement"),
            (29, "terms and conditions"),
            (30, "Updated at: "),
            (31, "Followers: "),
            (32, "CERTIFICATES"),
            (33, "COMPONENTS all"),
            (34, "fav COMPONENTS"),
            (35, "COMPANIES all"),
            (36, "fav COMPANIES"),
            (37, "fav STANDARDS"),
            (38, "fav USERS"),
            (39, " Position: "),
            (40, " Region: "),
            (41, " Working software: "),
            (42, "Hide info"),
            (43, "Show info"),
            (44, "Enter"),
            (45, "Create"),
        ]);
}
